### ISSUE TITLE
Export CSV: Test and Improve performances

### ISSUE THREAD

**Issue by LucasBrazi06** [Charge-Angels/ev-server#2057]
Check perfs with exporting 100k records (logs) (+= vs join()) and apply the most efficient one.

**Comment by cabch** [comment]
+ add tags export in sessions (tag description join with tag - {withTags: boolean} to add in transactionStorage

**Comment by cabch** [comment]
Do i really need to test with 100k + records ? we already have 10 sec apart with 24k records !! (winner is `+=` 🥇  export lasts 260 seconds)

**Comment by LucasBrazi06** [comment]
> Do i really need to test with 100k + records ? we already have 10 sec apart with 24k records !! (winner is `+=` 🥇 export lasts 260 seconds)

It's okay, anyway I limited the export to 100k records even if you requested millions ;-).
🥇 ?
So we go with the `+=` then right?

**Comment by cabch** [comment]
ok, yes we go with `+=` 
(🥇 = golden medal for the `+=` ... ;))

**Comment by LucasBrazi06** [comment]
> ok, yes we go with `+=`
> (🥇 = golden medal for the `+=` ... ;))

LOL
Okay :-)
So will you treat the add of the badge ID in session export in another issue?
