### ISSUE TITLE
OCPIPushLocationsTask > processOCPIEndpoint: Missing pushLocations request - no Locations are pushed

### ISSUE THREAD

**Issue by Jakob8** [Charge-Angels/ev-server#2113]
Investigate if the PushLocationsTask only pushes the EVSE Statuses and not all EVSEs / Locations
CpoOcpiClient has no method sendLocations or pushLocations

**Comment by LucasBrazi06** [comment]
@jerome-benoit Could you update the configuration in SCP & AWS?
Thanks!
